name: Build flutter apk

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
         channel: 'stable'
         cache: true
     
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: "17"
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        cache: true

      - run: flutter pub get
      - run: flutter clean
      - run: flutter build appbundle

